# Site Configuration
[site]
  title            = "marvindrone.com" # Shared title for SEO and OpenGraph
  description      = "Agenzia creativa e digitale realizzata con Astro e Tailwind CSS" # Shared description for SEO and OpenGraph
  tagline          = "Agenzia creativa e digitale"
  taglineSeparator = "" # default is " - " 
  baseUrl          = "https://marvindrone.com" # Base URL for the site and used in OpenGraph meta tags.
  logo             = "/images/logo.svg" # Path to the site's logo
  logoAlternate    = "" # Path to the site's logo
  logoText         = "marvindrone.com" # Text displayed next to the logo
  logoWidth        = "29px" # Width of the logo
  logoHeight       = "29px" # Height of the logo

  # Add a trailing slash at the end of URLs (e.g., https://example.com/, https://example.com/contact/)
  # Note: Manually restart your server when you change this value
  trailingSlash = true

  # Add your site logo in image path below and open your terminal and run "npm run generate-favicons" to generate favicons for different devices and platform (https://realfavicongenerator.net/checker)
  [site.favicon]
    path  = "/images/favicons" # favicon images path (No need to change it)
    image = "/images/logos/favicon.svg" # Add your site logo path here and follow upper instruction


# SEO Metadata
# Specific SEO configurations that complement the general site settings.
# -----------------------------------------------------------------------------------------------------------------------------------
[seo]
  author   = "marvindrone.com"
  keywords = ["agenzia digitale", "astro", "tailwind"] # SEO keywords
  robots   = "index, follow" # Instructs search engines on how to crawl and index the pages.

  [seo.robotsTxt]
    enable   = true # Enables or disables robots.txt file generation on site build
    disallow = [] # Disallow specific paths (e.g., "/_astro/", "/cdn-cgi/")

  [seo.sitemap]
    enable  = true # Enables or disables sitemap generation on site build
    exclude = [] # exclude all pages that include these folder names


# Different theme settings
# -----------------------------------------------------------------------------------------------------------------------------------
[settings]
  # If you change value of any of the following three, make sure to change the folder name also from
  # - "src/content" folder
  # - "src/[...lang]/pages" folder
  # - "src/content.config.ts" collection object
  blogFolder      = "blog" # Folder where blog posts are stored
  servicesFolder  = "services" # Folder where services are stored
  portfolioFolder = "case-studies" # Folder where case-studies or projects or portfolio are stored

  pagination   = 4 # Number of posts displayed on each page blog list page
  stickyHeader = true # Enables or disable sticky feature of header
  brandName    = "marvindrone.com" # Name to be displayed in the footer as big text

  # docs - https://formspree.io/ | https://formsubmit.co/ | https://docs.netlify.com/forms/setup/
  # Form action URL for the contact form (For more settings related to form see "src/content/sections/contact-section.md")
  contactFormAction = "https://formsubmit.co/info@marvindrone.com" # https://formspree.io/f/kweoweo | https://formsubmit.co/your@email.com | "/"
  # formspree | formsubmit.co | netlify (default is formsubmit.co)
  contactFormProvider = "formsubmit.co"

  footerDescription = ""

  [settings.copyright]
    enable = true
    text   = ""

  # Mailchimp Subscription Form located in footer
  [settings.subscription]
    enable     = true # Enables or disable the subscription form
    title      = ""
    formAction = "https://gmail.us11.list-manage.com/subscribe/post?u=d870b06d86c16269e4b1f9b39&amp;id=12cf0c6ac2&amp;f_id=007e61e1f0"

  # Navigation Button In Header
  [settings.navigationButton]
    enable   = true
    label    = "Contattaci"
    url      = "/contact/"
    showIcon = "true" # "true" or "false"
    # hoverEffect = "text-flip" # "text-flip", "creative-fill", "magnetic", "magnetic-text-flip"

  [settings.markup.tableOfContents]
    enable     = true
    expanded   = true # whether to expand the table of contents by default
    endLevel   = 5
    ordered    = false
    startLevel = 1


# OpenGraph Metadata
# Specific OpenGraph settings, using values from the [site] section where possible.
# -----------------------------------------------------------------------------------------------------------------------------------
[opengraph]
  image       = "/images/og-image.png" # Image used in OpenGraph previews
  ogLocale    = "it_IT" # Locale setting for OpenGraph
  ogType      = "website" # Type of content for OpenGraph protocol
  twitter     = "" # Twitter handle for Twitter Card meta tags
  twitterCard = "summary_large_image" # Type of Twitter Card to use in social sharing

# [head] (Add custom scripts, stylesheets, and meta tags to be rendered in the <head> section of the page)
# -----------------------------------------------------------------------------------------------------------------------------------
[head]
  content = """
  <!-- You can easily add this type of tracking code by updating the `config.toml` file -->
  <script defer src="/umami.is.js" data-website-id=""></script>
  """
